-- MySQL Script generated by yy captain's hands
-- Sat Mar 14 22:00:00 2020
-- Model: New Model    Version: 1.0
-- Email: gaoyang615@163.com
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_harbour
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `db_harbour` ;

-- -----------------------------------------------------
-- Schema db_harbour
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_harbour` DEFAULT CHARACTER SET utf8 ;
USE `db_harbour` ;

-- -----------------------------------------------------
-- Table `db_harbour`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_harbour`.`users` ;

CREATE TABLE IF NOT EXISTS `db_harbour`.`users` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `pin` VARCHAR(64) NOT NULL COMMENT '用户唯一标识',
  `name` VARCHAR(64) NOT NULL COMMENT '用户名',
  `password` VARCHAR(64) NOT NULL COMMENT '用户密码',
  `phone` VARCHAR(64) DEFAULT '' COMMENT '手机号码',
  `email` VARCHAR(64) DEFAULT '' COMMENT '邮箱',
  `gender` INT(11) DEFAULT 0 COMMENT '性别 0 未知 1 男 2 女',
  `sign_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '注册时间',
  `level` INT(11) NOT NULL DEFAULT 0 COMMENT '用户等级',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `pin_unique` (`pin` ASC))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Data for table `db_harbour`.`users`
-- -----------------------------------------------------
START TRANSACTION;
USE `db_harbour`;
INSERT INTO `db_harbour`.`users` (`pin`, `name`, `password`) VALUES ('god', 'god', 'hands_of_god');
COMMIT;

